zuul:
  ignored-services: "*"
  prefix: /gateway #访问前缀
  routes:
    api-a: #随意起的名字
      path: /api-url/**  #映射地址
      serviceId: client01 #注册中心的服务名
    api-b:
      path: /api-url-client02/**
      serviceId: client02
# ribbon:
#   eureka:
#     enabled: false
